title: "مواثيق"
email: hassan.aljaezi.law@gmail.com
description: >-
  خدمات قانونية رقمية تشمل مراجعة المذكرات القانونية، تدقيق إملائي قانوني، استشارات قانونية عن بعد، وإعداد العقود.

baseurl: "" 
url: "https://moathiq-project.github.io" 
lang: ar

# Social media
twitter_username: "" 
github_username: moathiq-project

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
